### ISSUE TITLE
프로젝트 세팅 및 환경 설정

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/fe-vm#1]
## 📃 Description
CRA로 프로젝트를 생성하고 환경 설정 및 구조 설계를 진행한다. 

## ☑ Todo
- [x] 피그마를 사용해 디자인 개선
- [x] 요구사항 분석
- [x] Prettier
- [x] ESLint (에어비엔비 스타일 가이드 적용)
- [x] 절대 경로 설정
- [x] eslint-plugin-import 적용
- [x] Storybook, Styled-component 설치
