### ISSUE TITLE
레이아웃 완성

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/fe-vm#18]
## 📃 Description

Molecule, Organism 조합을 마무리하고 자판기 정보, 지갑을 만들어 렌더링한다.

## ☑ Todo
- [x] 자판기 정보의 SelectForm Molecule
- [x] 지갑의 MoneyCounter Molecule, MoneyCounters Organism
- [x] 자판기 정보, 지갑 조립하기
- [x] 페이지에 모두 렌더링
