### ISSUE TITLE
json-server 설정

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/fe-vm#20]
## 📃 Description

products, wallet 데이터를 json-server로 관리한다.
페이지 렌더링 시 json-server에서 데이터를 가져오도록 한다.

## ☑ Todo
- [x] db.json 생성, 데이터 등록
- [x] ~~useFetch 커스텀 훅 생성~~ useAsync로 변경
- [x] 데이터 가져와서 렌더링
