### ISSUE TITLE
[Feat] 자판기 돈 투입 기능 구현

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/fe-vm#22]
## 📃 Description

- [스토리 2](https://github.com/mina-gwak/fe-vm/wiki/%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EB%B6%84%EC%84%9D#%EC%8A%A4%ED%86%A0%EB%A6%AC-2), [스토리 3](https://github.com/mina-gwak/fe-vm/wiki/%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EB%B6%84%EC%84%9D#%EC%8A%A4%ED%86%A0%EB%A6%AC-3) 일부 구현
- 총 투입 금액을 전역 상태로 관리한다.
- 입력창과 드롭다운을 통해 넣을 금액을 입력하면 총 투입 금액에 반영되도록 한다.

## ☑ Todo
- [x] 총 투입 금액 context 생성
- [x] 입력창, 드롭다운에서 금액을 입력하면 총 투입 금액에 반영한다.
- [x] 총 투입 금액에 따라 구입할 수 있는 상품 목록을 갱신한다.
