### ISSUE TITLE
글로벌 스타일 적용 및 페이지 정보 변경

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/fe-vm#3]
## 📃 Description
컴포넌트와 스토리에 글로벌 스타일을 적용하고, 페이지 정보를 프로젝트에 맞게 변경한다.

## ☑ Todo
- [x] 글로벌 스타일 생성
- [x] 컴포넌트에 글로벌 스타일 적용
- [x] 스토리 전체에 글로벌 스타일 적용
- [x] 페이지 정보, favicon 변경
